-- AlterTable
ALTER TABLE `Establishment` ADD COLUMN `cep` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `latitude` FLOAT NOT NULL DEFAULT 0.0,
    ADD COLUMN `longitude` FLOAT NOT NULL DEFAULT 0.0;

-- AlterTable
ALTER TABLE `users` ADD COLUMN `cep` INTEGER NULL DEFAULT 0,
    ADD COLUMN `latitude` FLOAT NOT NULL DEFAULT 0.0,
    ADD COLUMN `longitude` FLOAT NOT NULL DEFAULT 0.0;
